name: build-and-push

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: self-hosted
    env:
      IMAGE: yourdockerhubuser/your-app
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl -n app set image deployment/sample-app sample-app=${IMAGE}:${TAG}
          kubectl -n app rollout status deployment/sample-app --timeout=180s
